version: '3.4'
services:
  redis:
    image: redis
    env_file:
      - .env
    container_name: gamma_redis
    ports:
      - "6379:6379"
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: gamma_celery
    depends_on:
      - redis
    command: [celery, -A, tasks, worker, --loglevel=INFO]

  flower:
    image: mher/flower
    env_file:
      - .env
    container_name: celery_flower
    depends_on:
      - redis
      - celery
    ports:
      - "5555:5555"
    command: [celery, --broker=redis://redis:6379/0, flower, --port=5555, --max_tasks=1000000]

  minio:
    #    image: minio/minio
    build:
      context: .
      dockerfile: .minio/Dockerfile
    env_file:
      - ./.env
    environment:
      - MINIO_HOST=minio
    container_name: gamma_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./.minio/data:/data
    command: /bin/sh -c /opt/miniosetup.sh

