version: '3.4'
services:
  redis:
    image: redis
    container_name: gamma_redis
    ports:
      - "6379:6379"
  celery:
    build:
      context: .
      dockerfile: CeleryDockerfile
    container_name: gamma_celery
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    command: [celery, -A, tasks, worker, --loglevel=INFO, --concurrency=4]

  flower:
    image: mher/flower
    container_name: celery_flower
    depends_on:
      - redis
      - celery
    ports:
      - "5555:5555"
    command: [flower, --port=5555, --broker=redis://redis:6379/0]